services:
  selenium:
    image: selenium/standalone-chrome:dev
    shm_size: '2gb'
    ports:
      - 4444:4444
      - 5900:5900
      - 7900:7900
    networks:
      - selenium-net
  bing:
    build: .
    tty: true
    command: python3 main.py
    networks:
      - selenium-net
networks:
  selenium-net:
    name: bing-selenium-bridge